apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  DB_HOST: "tf-db.ccitclnvbmiv.ap-northeast-2.rds.amazonaws.com"  # Terraform output ê°’
  DB_PORT: "3306"
  DB_NAME: "mydb"
